// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-atj9X9Qap9HchlOoMQgynqyGJj88y5o',
    appId: '1:590226953929:web:eca434494c2c82bb785f18',
    messagingSenderId: '590226953929',
    projectId: 'social-7b27c',
    authDomain: 'social-7b27c.firebaseapp.com',
    storageBucket: 'social-7b27c.appspot.com',
    measurementId: 'G-P14R65YFM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-3uh8V5m9qR5a8A93hFVirrlxHExUx5s',
    appId: '1:590226953929:android:87cb7a2c67b5daf8785f18',
    messagingSenderId: '590226953929',
    projectId: 'social-7b27c',
    storageBucket: 'social-7b27c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEx33-gBmPQOidy3ubM_n72bZD8Gl9LMw',
    appId: '1:590226953929:ios:894d3e56b6542b04785f18',
    messagingSenderId: '590226953929',
    projectId: 'social-7b27c',
    storageBucket: 'social-7b27c.appspot.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEx33-gBmPQOidy3ubM_n72bZD8Gl9LMw',
    appId: '1:590226953929:ios:ca1d5ffd62b89ac3785f18',
    messagingSenderId: '590226953929',
    projectId: 'social-7b27c',
    storageBucket: 'social-7b27c.appspot.com',
    iosBundleId: 'com.chronoverse.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-atj9X9Qap9HchlOoMQgynqyGJj88y5o',
    appId: '1:590226953929:web:c34cd7d41d22a874785f18',
    messagingSenderId: '590226953929',
    projectId: 'social-7b27c',
    authDomain: 'social-7b27c.firebaseapp.com',
    storageBucket: 'social-7b27c.appspot.com',
    measurementId: 'G-YJWP39V46Q',
  );
}
